insert into artist(email, password, nickname, registrationDate)
values ('artist1@art.com', 'artist1', 'artist1', NOW()),
       ('artist2@art.com', 'artist2', 'artist2', now()),
       ('artist3@art.com', 'artist3', 'artist3', now()),
       ('artist4@art.com', 'artist4', 'artist4', now()),
       ('artist5@art.com', 'artist5', 'artist5', now()),
       ('artist6@art.com', 'artist6', 'artist6', now()),
       ('artist7@art.com', 'artist7', 'artist7', now()),
       ('artist8@art.com', 'artist8', 'artist8', now()),
       ('artist9@art.com', 'artist9', 'artist9', now()),
       ('artist10@art.com', 'artist10', 'artist10', now()),
       ('artist11@art.com', 'artist11', 'artist11', now()),
       ('artist12@art.com', 'artist12', 'artist12', now()),
       ('artist13@art.com', 'artist13', 'artist13', now()),
       ('artist14@art.com', 'artist14', 'artist14', now()),
       ('artist15@art.com', 'artist15', 'artist15', now()),
       ('artist16@art.com', 'artist16', 'artist16', now()),
       ('artist17@art.com', 'artist17', 'artist17', now()),
       ('artist18@art.com', 'artist18', 'artist18', now()),
       ('artist19@art.com', 'artist19', 'artist19', now()),
       ('artist20@art.com', 'artist20', 'artist20', now()),
       ('artist21@art.com', 'artist21', 'artist21', now()),
       ('artist22@art.com', 'artist22', 'artist22', now()),
       ('artist23@art.com', 'artist23', 'artist23', now());